spring:
  profiles:
    active: development
  thymeleaf:
    prefix: file:src/main/resources/templates/
  jpa:
    show-sql: false
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    url: jdbc:mysql://localhost:3306/shoes2
    username: root
    password: 123456

  telegram:
    bot:
      username: ShoesHot_Bot
      token: 6757918465:AAEVzjycpYXZSkFuXzd4SOD7JCRglFTqx5E
    chat:
      id: 6867221430

  paypal:
    client:
      id: AeKcCsvc8UljUcdmaxSAyigFe0E8WM2Dpe0w9HAyKfGyJvf1rlXGCkNONYrcbj7NRYWqlRMWx-3ROeg4
      secret: EOw4K_JuGiy1rWRz7RDhybqBiTYE6zxVf0HEQ6y8fehpHgFrw9shgIBBDxy0JFzFxIOsvWdGgQrE9Hol
jwt:
  secret: super_secret
  duration: 604800




